/*
	Get Products
*/
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const REQUEST_PRODUCTS_FAIL = 'REQUEST_PRODUCTS_FAIL'
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY'

/*
	Add To Cart
*/

export const ADD_TO_CART = 'ADD_TO_CART'
export const NO_REMAINING_NOTICE = 'NO_REMAINING_NOTICE'

/*
	IN THE SHOPPING CART
*/

export const REQUEST_CHECKOUT = 'REQUEST_CHECKOUT'
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART'
